package rules

import (
	"context"

	"github.com/gauravdhanuka4/trade-detection-system/internal/models"
	"github.com/gauravdhanuka4/trade-detection-system/internal/redis"
	"github.com/google/uuid"
)

// Rule defines the interface for a fraud detection rule
type Rule interface {
	// Name returns the rule name
	Name() string

	// Type returns the risk type this rule detects
	Type() models.RiskType

	// Evaluate evaluates a trade against this rule using granular cache data
	// Returns an alert if the rule is triggered, nil otherwise
	Evaluate(ctx context.Context, trade *models.Trade, userProfile *redis.UserProfile, realtimeMetrics *redis.RealtimeMetrics, recentTrades []*models.Trade) (*models.Alert, error)

	// Severity returns the severity level for alerts generated by this rule
	Severity() models.SeverityType

	// IsEnabled returns whether this rule is currently enabled
	IsEnabled() bool

	// GetRuleID returns the database rule ID
	GetRuleID() uuid.UUID
}
