package models

import (
	"time"

	"github.com/google/uuid"
)

// Alert represents a risk alert generated by the detection system
type Alert struct {
	ID               uuid.UUID    `json:"id" db:"id"`
	TradeID          uuid.UUID    `json:"trade_id" db:"trade_id"`
	RuleID           *uuid.UUID   `json:"rule_id" db:"rule_id"` // nullable (ON DELETE SET NULL)
	RiskType         RiskType     `json:"risk_type" db:"risk_type"`
	Severity         SeverityType `json:"severity" db:"severity"`
	Status           AlertStatus  `json:"status" db:"status"`
	Description      *string      `json:"description" db:"description"`             // nullable
	DecisionCriteria *string      `json:"decision_criteria" db:"decision_criteria"` // JSONB stored as string, nullable
	CreatedAt        time.Time    `json:"created_at" db:"created_at"`
	UpdatedAt        time.Time    `json:"updated_at" db:"updated_at"`
}
